import discord,asyncio,os,json,re,cairosvg,shutil,subprocess,datetime
from time import perf_counter
from dotenv import load_dotenv
from zoneinfo import ZoneInfo
load_dotenv()
CHAT_LOG_FILE,USERS_FILE="chat.log","users.json"
open(CHAT_LOG_FILE,"a").close()
TOKEN,intents=os.getenv("DISCORD_TOKEN"),discord.Intents.default()
intents.presences,intents.members,intents.message_content=True,True,True
cirrus=discord.Client(intents=intents)
rainbows_and_clouds_server_id,rainbows_and_clouds_channel_id,clouds_channel_id=1511895185007579206,1534523744779763823,1534523821762281602
banned_words=[
    "nigger",
    "faggot",
    "retard",
    "nigga",
    "tranny",
    "semit",
    "maoist",
    "neomao",
]
banned_words=re.compile(r"\b(?:"+"|".join(map(re.escape,banned_words))+r")\b",re.IGNORECASE,)
def load_users():
    try:
        with open(USERS_FILE,"r") as file:
            return json.load(file)
    except FileNotFoundError:
        return{}
users=load_users()
def save_users(users):
    with open(USERS_FILE,"w") as file:
        json.dump(users,file,indent=4,ensure_ascii=False)
def generate_flag(code:str,username:str)->str:
    HEIGHT=5040
    WIDTH=HEIGHT*4//3
    HEX=set("0123456789abcdefABCDEF")
    text=code.strip().lower()
    circle="o" in text
    if circle:
        top_text,bottom_text=text.split("o",1)
        top_code="".join(c for c in top_text if c in HEX)
        bottom_code="".join(c for c in bottom_text if c in HEX)
        if not top_code or not bottom_code:
            raise ValueError("Circle flags need colors on both sides of o.")
        top_colors=[top_code[i:i+6]for i in range(0,len(top_code)-5,6)]
        bottom_colors=[bottom_code[i:i+6]for i in range(0,len(bottom_code)-5,6)]
        if not top_colors or not bottom_colors:
            raise ValueError("Each color must contain exactly 6 hexadecimal digits.")
        final_code=top_code+"o"+bottom_code
        size=HEIGHT
        center=size/2
        radius=center
        svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="100%" height="100%">\n<!-- Generated by {username} using Fiaguhop137\'s flag generator. The code used to generate this flag was {final_code} -->\n<defs>\n<clipPath id="top"><rect x="0" y="0" width="{size}" height="{center}"/></clipPath>\n<clipPath id="bottom"><rect x="0" y="{center}" width="{size}" height="{center}"/></clipPath>\n</defs>'
        top_ring_width=radius/len(top_colors)
        svg+='<g clip-path="url(#top)">\n'
        for index,color in enumerate(top_colors):
            ring_radius=radius-(index*top_ring_width)
            svg+=f'<circle cx="{center}" cy="{center}" r="{ring_radius}" fill="#{color}"/>\n'
        svg+='</g>\n'
        bottom_ring_width=radius/len(bottom_colors)
        svg+='<g clip-path="url(#bottom)">\n'
        for index,color in enumerate(bottom_colors):
            ring_radius=radius-(index*bottom_ring_width)
            svg+=f'<circle cx="{center}" cy="{center}" r="{ring_radius}" fill="#{color}"/>\n'
        svg+='</g>\n</svg>\n'
        return svg
    base_text,separator,chevron_text=text.partition(">")
    base_code="".join(c for c in base_text if c in HEX)
    chevron_code="".join(c for c in chevron_text if c in HEX) if separator else ""
    colors=[base_code[i:i+6]for i in range(0,len(base_code)-5,6)]
    chevron_colors=[chevron_code[i:i+6]for i in range(0,len(chevron_code)-5,6)]
    if not colors:
        raise ValueError("No valid 6-digit hexadecimal colors found.")
    final_code=base_code+(">"+chevron_code if separator else "")
    collapsed=[]
    for color in colors:
        if collapsed and collapsed[-1][0]==color:
            collapsed[-1]=(color,collapsed[-1][1]+1)
        else:
            collapsed.append((color,1))
    total_stripes=len(colors)
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%" height="100%">\n<!-- Generated by {username} using Fiaguhop137\'s flag generator. The code used to generate this flag was {final_code} -->\n'
    y=0
    for index,(color,count) in enumerate(collapsed):
        if index==len(collapsed)-1:
            height=HEIGHT-y
        else:
            height=count/total_stripes*HEIGHT
        svg+=f'<rect x="0" y="{y}" width="{WIDTH}" height="{height}" fill="#{color}"/>\n'
        y+=height
    if chevron_colors:
        triangle_inset=HEIGHT/(2*len(chevron_colors))
        for index,color in enumerate(chevron_colors):
            inset=index*triangle_inset
            tip=HEIGHT/2-inset
            svg+=(f'<polygon points="0,{inset} 'f'{tip},{HEIGHT/2} 'f'0,{HEIGHT-inset}" fill="#{color}"/>\n')
    svg+='</svg>\n'
    return svg
async def sync_roles(server:discord.Guild):
    cirrus_roles={}
    for role in server.roles:
        if role.name.isdigit():
            cirrus_roles[role.name]=role
    valid_users={str(user_id) for user_id in users}
    for role_id,role in cirrus_roles.items():
        role:discord.Role
        if role_id not in valid_users:
            await role.delete()
    for user_id in valid_users:
        member=server.get_member(int(user_id))
        if member is None:continue
        role=cirrus_roles.get(user_id)
        if role is None:
            role=await server.create_role(name=user_id,color=discord.Colour.default())
            await role.edit(color=discord.Colour(int(users[user_id]["color"],16)))
            cirrus_roles[user_id]=role
        for member_role in member.roles:
            if member_role.name.isdigit() and member_role.name!=user_id:
                await member.remove_roles(member_role)
        if role not in member.roles:
            await member.add_roles(role)
async def update_nickname(member:discord.Member):
    user=users.get(str(member.id))
    if user is None:return
    nickname=f'{user["name"]} ({user["pronouns"]})'
    if member.nick!=nickname:
        try:
            await member.edit(nick=nickname)
        except discord.HTTPException as e:
            await echo(f"Failed to update nickname: {e}",cirrus.get_channel(rainbows_and_clouds_channel_id))
            users[str(member.id)]["name"]="unknown"
            users[str(member.id)]["pronouns"]="try ~set or ~help"
            save_users(users)
async def echo(message,channel:discord.TextChannel):
    return await channel.send(message)
async def run_cmd(cmd:str,args:list,message:discord.Message):
    if cmd[0]!="~":
        return
    cmd=cmd.strip().lower()[1:]
    if cmd=="help":
        await echo('```markdown\n'
        ' ≈Available commands: \n'
        ' ~help                                  - Show this help message\n'
        ' ~ping                                  - Get the bot\'s latency\n'
        ' ~echo <message>                        - Echos the message back\n'
        ' ~set <name|pronouns|color> <value>     - Set your name, pronouns, or color\n'
        ' ~flag <code>                           - Generate a flag based on the provided hex color code\n'
        ' ~replay <lines>                        - Replay the last <lines> messages\n'
        ' ~reboot                                - Reboot the bot (lightning only)\n'
        ' ~purge <type> <etc>                    - Delete messages according to the specified type and parameters\n'
        '```',message.channel)
    elif cmd=="ping":
        start_time=perf_counter()
        pong=await echo(f"Pong! (calculating, please wait...)",message.channel)
        end_time=perf_counter()
        await pong.edit(content=f"pong!: {(cirrus.latency+end_time-start_time)*500:.2f}ms")
    elif cmd=="echo":
        await message.delete()
        await echo(" ".join(args),message.channel)
    elif cmd=="set":
        if len(args)<2:
            await echo("Usage: ~set <name|pronouns|color> <value>",message.channel)
            return
        key=args[0].lower()
        value=" ".join(args[1:])
        if key not in ["name","pronouns","color"]:
            await echo("Usage: ~set <name|pronouns|color> <value>",message.channel)
            return
        if key=="color":
                try:
                    color=int(value,16)
                except ValueError:
                    await echo("Color must be a valid 6 digit hexadecimal value, e.g. FFAA00.",message.channel)
                    return
                if color<0x000000 or color>0xFFFFFF or len(value)!=6:
                    await echo("Color must be a valid 6 digit hexadecimal value, e.g. FFAA00.",message.channel)
                    return
                users[str(message.author.id)][key]=value.upper()
                save_users(users)
                role=discord.utils.get(message.guild.roles,name=str(message.author.id))
                if role is not None:await role.edit(color=discord.Colour(color))
                await echo(f"I set your color to {value.upper()}!",message.channel)
                return
        users[str(message.author.id)][key]=value
        save_users(users)
        await sync_roles(message.guild)
        await update_nickname(message.author)
        await echo(f"I set your {key} to {value}!",message.channel)
    elif cmd=="flag":
        if not args:
            await echo("Usage: ~flag <hex color code>",message.channel)
            return
        code="".join(args)
        try:
            svg=generate_flag(code,users[str(message.author.id)]["name"])
            with open(f"{code}.svg","w") as svg_file:
                svg_file.write(svg)
            png_file=f"{code}.png"
            try:
                cairosvg.svg2png(bytestring=svg.encode("utf-8"),write_to=png_file,output_width=1200)
                await message.channel.send(file=discord.File(png_file,filename=png_file))
            finally:
                if os.path.exists(png_file):
                    os.remove(png_file)
                os.makedirs(f"/home/firebot/git/Flags/special/generated/{message.author.name}",exist_ok=True)
                shutil.move(f"/home/firebot/git/Rainbows and Clouds/{code}.svg",f"/home/firebot/git/Flags/special/generated/{message.author.name}/{code}.svg")
                subprocess.run(["git","sync"])
                m=await echo(f"You can find the svg version [here](<https://github.com/Fiaguhop137/Flags/blob/main/special/generated/{message.author.name}/{code}.svg>)",message.channel)
        except ValueError as e:
            await echo(f"Invalid flag code: {e}",message.channel)
        except Exception as e:
            await echo(f"Failed to generate flag: {e}",message.channel)
    elif cmd=="replay":
        if not args:
            await echo("Usage: ~replay <message count>",message.channel)
            return
        chat_logs=[]
        try:
            lines=int(args[0])
        except ValueError:
            await echo("Message count must be a valid integer.",message.channel)
            return
        try:
            with open(CHAT_LOG_FILE,"r") as chat_log:
                chat_logs=chat_log.readlines()
        except FileNotFoundError:
            await echo("No chat log found.",message.channel)
            return
        if lines<=0:
            await echo("Message count must be a positive integer.",message.channel)
            return
        if lines>len(chat_logs):
            lines=len(chat_logs)
        if lines>100:
            lines=100
        chat_logs=chat_logs[-lines:]
        for line in chat_logs:
            await echo(line,message.channel)
    elif cmd=="reboot":
        if "lightning" not in [role.name for role in message.author.roles]:
            await echo("You are not authorized to use this command.",message.channel)
            return
        await echo("Rebooting...",message.channel)
        reboot="/home/firebot/git/Rainbows-and-Clouds/restart_cirrus.sh"
        os.execv(reboot,[reboot])
    elif cmd=="purge":
        purge_type=args[0].lower() if args else ""
        if purge_type=="bots":
            if "cloud" not in [role.name for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<2:
                await echo("Usage: ~purge bots <count>",message.channel)
                return
            deleted=await message.channel.purge(limit=int(args[1]) if len(args)>1 else 100,check=lambda m:m.author.bot)
            await echo(f"Deleted {len(deleted)} bot messages.",message.channel)
        elif purge_type=="user":
            if "cloud" not in [role.name for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<3:
                await echo("Usage: ~purge user <user_id> <count>",message.channel)
                return
            try:
                user_id=int(args[1])
            except ValueError:
                await echo("User ID must be a valid integer.",message.channel)
                return
            count=int(args[2]) if len(args)>2 else 100
            deleted=await message.channel.purge(limit=count,check=lambda m:m.author.id==user_id)
            await echo(f"Deleted {len(deleted)} messages from user {user_id}.",message.channel)
        elif purge_type=="nuke":
            if "Plasma" not in [role.name for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            nuke_type=args[1].lower() if len(args)>1 else ""
            if nuke_type=="bots":
                if "cloud" not in [role.name for role in message.author.roles]:
                    await echo("You are not authorized to use this command.",message.channel)
                    return
                while await message.channel.purge(limit=100,check=lambda m:m.author.bot):pass
                await echo("Deleted all bot messages.",message.channel)
            elif nuke_type=="user":
                if "cloud" not in [role.name for role in message.author.roles]:
                    await echo("You are not authorized to use this command.",message.channel)
                    return
                if len(args)<3:
                    await echo("Usage: ~purge nuke user <user_id>",message.channel)
                    return
                try:
                    user_id=int(args[2])
                except ValueError:
                    await echo("User ID must be a valid integer.",message.channel)
                    return
                while await message.channel.purge(limit=100,check=lambda m:m.author.id==user_id):
                    pass
                await echo(f"Deleted all messages from user {user_id}.",message.channel)
            else:
                while await message.channel.purge(limit=100):
                    pass
                await echo("Deleted all messages.",message.channel)
        else:
            if "cloud" not in [role.name for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<1:
                await echo("Usage: ~purge <count>",message.channel)
                return
            try:
                count=int(args[0])
            except ValueError:
                await echo("Count must be a valid integer.",message.channel)
                return
            deleted=await message.channel.purge(limit=count)
            await echo(f"Deleted {len(deleted)} messages.",message.channel)
    else:
        await echo(f"Unknown command: {cmd}. Type ~help for a list of commands.",message.channel)
@cirrus.event
async def on_guild_join(server:discord.Guild):
    try:
        if server.id!=rainbows_and_clouds_server_id:
            valid_channels=[channel for channel in server.text_channels if channel.permissions_for(server.me).view_channel and channel.permissions_for(server.me).send_messages] 
            if not valid_channels:
                raise ValueError("No valid channels found")
            await echo(f"Why did you add me? This bot is only for the Rainbows and Clouds server.",valid_channels[0])
            raise ValueError("Invalid server found")
        else:
            await echo("Hello! I'm Cirrus, a discord bot for the Rainbows and Clouds server. Type ~help for a list of commands.",cirrus.get_channel(rainbows_and_clouds_channel_id))    
    except:
        await server.leave()
        return
@cirrus.event
async def on_message(message:discord.Message):
    if message.author==cirrus.user:
        return
    if str(message.author.id) not in users:
        users[str(message.author.id)]={"name":"unknown","pronouns":"try ~set or ~help","color":"000000","offenses":"0"}
        save_users(users)
    try: 
        int(users[str(message.author.id)]["offenses"])
    except KeyError:
        users[str(message.author.id)]["offenses"]="0"
        save_users(users)
    violations=users[str(message.author.id)]["offenses"]
    if message.guild is None:
        await message.author.send("I don't support DMs. Please use me in the Rainbows and Clouds server.")
        return
    if message.author.bot:
        await asyncio.sleep(1)
    parts=message.content.split()
    if not parts:
        return
    cmd=parts[0]
    args=parts[1:]
    with open(CHAT_LOG_FILE,"r") as chat_log:
        lines=chat_log.readlines()
        if message.content.strip()==lines[-1].split("):")[-1].strip() and lines[-1].split("(")[-1].split(")")[0].strip()==str(message.author.id):
            await message.delete()
            users[str(message.author.id)]["offenses"]=str(int(users[str(message.author.id)]["offenses"])+1)
            save_users(users)
    with open(CHAT_LOG_FILE,"a") as chat_log:
        chat_log.write(f"[{datetime.datetime.now(ZoneInfo('America/New_York')).isoformat()}, {message.guild}/{message.channel}] {message.author}({message.author.id}): {message.content}\n")
    if banned_words.search(message.content):
        await message.delete()
        await echo(f"{message.author.mention}, that message was flagged as offensive, inappropriate, and/or vulgar. Ping a cloud if you believe this is a mistake.",message.channel)
        await echo(f"Deleted message from {message.author} in {message.guild}/{message.channel}: {message.content}",cirrus.get_channel(clouds_channel_id))
        users[str(message.author.id)]["offenses"]=str(int(users[str(message.author.id)]["offenses"])+1) if "offenses" in users[str(message.author.id)] else 1
        save_users(users)
    if violations!=users[str(message.author.id)]["offenses"]:
        violations=users[str(message.author.id)]["offenses"]
        if int(violations)>5:
            await echo(f"{message.author.mention}, you have been muted for repeated violations(e.g., spamming, hate speech, etc.). Please contact a cloud if you believe this is a mistake.",message.channel)
            await echo(f"{message.author} has been muted for {violations} violations.",cirrus.get_channel(clouds_channel_id))
            await message.author.edit(timed_out_until=discord.utils.utcnow()+datetime.timedelta(seconds=int(violations)*10),reason=f"{violations} violations of the rules. ")
        return
    else:
        users[str(message.author.id)]["offenses"]=str(int(users[str(message.author.id)]["offenses"])-1) if int(users[str(message.author.id)]["offenses"])-1>0 else "0"
    save_users(users)
    await sync_roles(message.guild)
    await update_nickname(message.author)
    await run_cmd(cmd,args,message)
    await sync_roles(message.guild)
    await update_nickname(message.author)
@cirrus.event
async def on_member_join(member:discord.Member):
    await sync_roles(member.guild)
    await update_nickname(member)
    await echo(f"Hi {member.mention}! Welcome to the Rainbows and Clouds server! Type ~help for a list of commands. ",cirrus.get_channel(rainbows_and_clouds_channel_id))
@cirrus.event
async def on_member_update(before:discord.Member,after:discord.Member):
    if before.nick!=after.nick:
        await update_nickname(after)
@cirrus.event
async def on_ready():
    server=cirrus.get_guild(rainbows_and_clouds_server_id)
    if server is None:
        return
    await sync_roles(server)
    for user in server.members:
        await update_nickname(user)
    await echo(f"Cirrus has rebooted! Type ~help for a list of commands.",cirrus.get_channel(rainbows_and_clouds_channel_id))
cirrus.run(TOKEN)
