import discord,asyncio,os,json,re,cairosvg,shutil,subprocess,datetime
from time import perf_counter
from dotenv import load_dotenv
from zoneinfo import ZoneInfo
load_dotenv()
CHAT_LOG_FILE="chat.log"
USERS_FILE="users.json"
ROLES_FILE="roles.json"
open(CHAT_LOG_FILE,"a").close()
TOKEN=os.getenv("DISCORD_TOKEN")
intents=discord.Intents.default()
intents.presences=True
intents.members=True
intents.message_content=True
cirrus=discord.Client(intents=intents)
rainbows_and_clouds_server_id=1511895185007579206
rainbows_and_clouds_channel_id=1534523744779763823
clouds_channel_id=1534523821762281602
LIGHTNING_ROLE_ID=1554641502167105687
CLOUDS_ROLE_ID=1534523120323395626
SUN_ROLE_ID=1534523571542691881
banned_words=[
    "nigger",
    "faggot",
    "retard",
    "nigga",
    "tranny",
    "semit",
    "maoist",
    "neomao",
    "easton",
    "amara",
    "issac",
]
banned_words=re.compile(r"\b(?:"+"|".join(map(re.escape,banned_words))+r")\b",re.IGNORECASE,)
def load_users():
    try:
        with open(USERS_FILE,"r") as file:return json.load(file)
    except FileNotFoundError:return {}
def save_users(users):
    with open(USERS_FILE,"w") as file:json.dump(users,file,indent=4,ensure_ascii=False)
def load_roles():
    try:
        with open(ROLES_FILE,"r") as file:return json.load(file)
    except FileNotFoundError:return {}
def save_roles(roles):
    with open(ROLES_FILE,"w") as file:
        json.dump(roles,file,indent=4,ensure_ascii=False)
users=load_users()
roles=load_roles()
def ensure_user_roles():
    changed=False
    for user in users.values():
        if "roles" not in user or not isinstance(user["roles"],list):
            user["roles"]=[]
            changed=True
    if changed:save_users(users)
ensure_user_roles()
def generate_flag(code:str,username:str)->str:
    HEIGHT=5040
    WIDTH=HEIGHT*4//3
    HEX=set("0123456789abcdefABCDEF")
    text=code.strip().lower()
    circle="o" in text
    if circle:
        top_text,bottom_text=text.split("o",1)
        top_code="".join(c for c in top_text if c in HEX)
        bottom_code="".join(c for c in bottom_text if c in HEX)
        if not top_code or not bottom_code:raise ValueError("Circle flags need colors on both sides of o.")
        top_colors=[top_code[i:i+6]for i in range(0,len(top_code)-5,6)]
        bottom_colors=[bottom_code[i:i+6]for i in range(0,len(bottom_code)-5,6)]
        if not top_colors or not bottom_colors:
            raise ValueError("Each color must contain exactly 6 hexadecimal digits.")
        final_code=top_code+"o"+bottom_code
        size=HEIGHT
        center=size/2
        radius=center
        svg=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="100%" height="100%"><!-- Generated by {username} using Fiaguhop137's flag generator. The code used to generate this flag was {final_code} --><defs><clipPath id="top"><rect x="0" y="0" width="{size}" height="{center}"/></clipPath><clipPath id="bottom"><rect x="0" y="{center}" width="{size}" height="{center}"/></clipPath></defs>'''
        top_ring_width=radius/len(top_colors)
        svg+='<g clip-path="url(#top)">'
        for index,color in enumerate(top_colors):
            ring_radius=radius-(index*top_ring_width)
            svg+=(f'<circle cx="{center}" cy="{center}" 'f'r="{ring_radius}" fill="#{color}"/>')
        svg+='</g>'
        bottom_ring_width=radius/len(bottom_colors)
        svg+='<g clip-path="url(#bottom)">'
        for index,color in enumerate(bottom_colors):
            ring_radius=radius-(index*bottom_ring_width)
            svg+=(f'<circle cx="{center}" cy="{center}" 'f'r="{ring_radius}" fill="#{color}"/>')
        svg+='</g></svg>'
        return svg
    base_text,separator,chevron_text=text.partition(">")
    base_code="".join(c for c in base_text if c in HEX)
    chevron_code=("".join(c for c in chevron_text if c in HEX)if separator else "")
    colors=[base_code[i:i+6]for i in range(0,len(base_code)-5,6)]
    chevron_colors=[chevron_code[i:i+6]for i in range(0,len(chevron_code)-5,6)]
    if not colors:raise ValueError("No valid 6-digit hexadecimal colors found.")
    final_code=base_code+(">"+chevron_code if separator else "" )
    collapsed=[]
    for color in colors:
        if collapsed and collapsed[-1][0]==color:collapsed[-1]=(color,collapsed[-1][1]+1)
        else:collapsed.append((color,1))
    total_stripes=len(colors)
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%" height="100%"><!-- Generated by {username} using Fiaguhop137's flag generator. The code used to generate this flag was {final_code} -->'''
    y=0
    for index,(color,count) in enumerate(collapsed):
        if index==len(collapsed)-1:height=HEIGHT-y
        else:height=count/total_stripes*HEIGHT
        svg+=(f'<rect x="0" y="{y}" width="{WIDTH}" 'f'height="{height}" fill="#{color}"/>\n')
        y+=height
    if chevron_colors:
        triangle_inset=HEIGHT/(2*len(chevron_colors))
        for index,color in enumerate(chevron_colors):
            inset=index*triangle_inset
            tip=HEIGHT/2-inset
            svg+=(f'<polygon points="0,{inset} 'f'{tip},{HEIGHT/2} 'f'0,{HEIGHT-inset}" fill="#{color}"/>\n')
    svg+='</svg>\n'
    return svg
async def echo(message,channel:discord.TextChannel):return await channel.send(message)
def role_permissions(role_data):return discord.Permissions(role_data.get("permissions",0))
def role_color(role_data):
    try:return discord.Colour(int(role_data.get("color","000000"),16))
    except (ValueError,TypeError):return discord.Colour.default()
async def sync_roles(server:discord.Guild):
    ensure_user_roles()
    numbered_roles={}
    for role in server.roles:
        if role.name.isdigit():numbered_roles[role.name]=role
    valid_users={str(user_id)for user_id in users}
    for role_id,role in list(numbered_roles.items()):
        if role_id not in valid_users:
            try:await role.delete(reason="User no longer exists in users.json")
            except discord.HTTPException:pass
    for user_id in valid_users:
        member=server.get_member(int(user_id))
        if member is None:continue
        role=numbered_roles.get(user_id)
        color=role_color(users[user_id])
        if role is None:
            try:
                role=await server.create_role(name=user_id,color=color,reason="Cirrus user role")
                numbered_roles[user_id]=role
            except discord.HTTPException:continue
        elif role.color.value!=color.value:
            try:await role.edit(color=color,reason="Cirrus user role synchronization")
            except discord.HTTPException:pass
    discord_named_roles={role.name:role for role in server.roles if not role.name.isdigit()and not role.is_default()}
    configured_role_names=set(roles.keys())
    for role_name,role in list(discord_named_roles.items()):
        if role_name not in configured_role_names:
            try:await role.delete(reason="Role is not defined in roles.json")
            except discord.HTTPException:pass
    for role_name,role_data in roles.items():
        if role_name.isdigit():
            continue
        role=discord.utils.get(server.roles,name=role_name)
        if role is None:
            try:
                role=await server.create_role(name=role_name,color=role_color(role_data),permissions=role_permissions(role_data),reason="Role defined in roles.json")
            except discord.HTTPException as e:
                await echo(f"Failed to create role `{role_name}`: {e}",cirrus.get_channel(clouds_channel_id))
                continue
        else:
            try:
                color=role_color(role_data)
                permissions=role_permissions(role_data)
                if(role.color.value!=color.value or role.permissions.value!=permissions.value):await role.edit(color=color,permissions=permissions,reason="roles.json synchronization")
            except discord.HTTPException as e:await echo(f"Failed to update role `{role_name}`: {e}",cirrus.get_channel(clouds_channel_id))
    discord_named_roles={role.name:role for role in server.roles if not role.name.isdigit() and not role.is_default() and not role.managed}
    configured_role_names=set(roles.keys())
    for role_name,role in list(discord_named_roles.items()):
        if role_name not in configured_role_names:
            try:await role.delete(reason="Role is not defined in roles.json")
            except discord.HTTPException:pass
    for role_name,role_data in roles.items():
        if role_name.isdigit():continue
        expected_color=role_color(role_data)
        expected_permissions=role_permissions(role_data)
        role=discord.utils.get(server.roles,name=role_name)
        if role is None:
            try:role=await server.create_role(name=role_name,color=expected_color,permissions=expected_permissions,reason="Role defined in roles.json")
            except discord.HTTPException as e:await echo(f"Failed to create role `{role_name}`: {e}",cirrus.get_channel(clouds_channel_id))
            continue
        if role.color.value!=expected_color.value:
            try:await role.edit(color=expected_color,reason="roles.json color synchronization")
            except discord.HTTPException as e:await echo(f"Failed to update color for role `{role_name}`: {e}",cirrus.get_channel(clouds_channel_id))
        if role.permissions.value!=expected_permissions.value:
            try:await role.edit(permissions=expected_permissions,reason="roles.json permission synchronization")
            except discord.HTTPException as e:await echo(f"Failed to update permissions for role `{role_name}`: {e}",cirrus.get_channel(clouds_channel_id))
    for user_id,user_data in users.items():
        member=server.get_member(int(user_id))
        if member is None:
            continue
        wanted_roles=[]
        numbered_role=numbered_roles.get(user_id)
        if numbered_role is not None:wanted_roles.append(numbered_role)
        for role_name in user_data.get("roles",[]):
            role=discord_named_roles.get(role_name)
            if role is not None:wanted_roles.append(role)
        wanted_ids={role.id for role in wanted_roles}
        for member_role in list(member.roles):
            if member_role.is_default():continue
            if member_role.id not in wanted_ids:
                try:await member.remove_roles(member_role,reason="Cirrus role synchronization")
                except discord.HTTPException:pass
        for role in wanted_roles:
            if role not in member.roles:
                try:await member.add_roles(role,reason="Cirrus role synchronization")
                except discord.HTTPException:pass
async def update_nickname(member:discord.Member):
    user=users.get(str(member.id))
    if user is None:return  
    nickname=f'{user["name"]} ({user["pronouns"]})'
    if user["pronouns"].lower()=="neo":nickname=f'{user["name"]}'
    if member.nick!=nickname:
        try:await member.edit(nick=nickname)
        except discord.HTTPException as e:
            await echo(f"Failed to update nickname: {e}",cirrus.get_channel(rainbows_and_clouds_channel_id))
            users[str(member.id)]["name"]="unknown"
            users[str(member.id)]["pronouns"]="try ~set or ~help"
            save_users(users)
def has_role(member,role_name):
    return any(role.name==role_name for role in member.roles)
def resolve_member(guild:discord.Guild,member_identifier:str):
    member_identifier=member_identifier.strip("<@!>")
    member=guild.get_member(int(member_identifier))if member_identifier.isdigit()else None
    if member is not None:return member
    for m in guild.members:
        if m.name.lower()==member_identifier.lower()or(m.nick and m.nick.lower()==member_identifier.lower()):
            return m
    return None
async def run_cmd(cmd:str,args:list,message:discord.Message):
    if cmd[0]!="~":return
    cmd=cmd.strip().lower()[1:]
    if cmd=="help":
        await echo(
            '```markdown\n'
            ' ≈Available commands: \n'
            ' ~help                                  - Show this help message\n'
            ' ~ping                                  - Get the bot\'s latency\n'
            ' ~echo <message>                        - Echos the message back\n'
            ' ~set <name|pronouns|color> <value>     - Set your name, pronouns, or color\n'
            ' ~flag <code>                           - Generate a flag based on the provided hex color code\n'
            ' ~replay <lines>                        - Replay the last <lines> messages\n'
            ' ~reboot                                - Reboot the bot (lightning only)\n'
            ' ~purge <type> <etc>                    - Delete messages according to the specified type and parameters\n'
            ' ~role add <role>                       - Add a role to a member (cloud only)\n'
            ' ~role remove <role>                    - Remove a role from a member (cloud only)\n'
            ' ~role new <name>                       - Create a role (cloud only)\n'
            ' ~role delete <name>                    - Delete a role (cloud only)\n'
            '```',
            message.channel
        )
    elif cmd=="ping":
        start_time=perf_counter()
        pong=await echo("Pong! (calculating, please wait...)",message.channel)
        end_time=perf_counter()
        await pong.edit(content=f"pong!: {(cirrus.latency+end_time-start_time)*500:.2f}ms")
    elif cmd=="echo":
        await message.delete()
        await echo(" ".join(args),message.channel)
    elif cmd=="set":
        if len(args)<2:
            await echo("Usage: ~set <name|pronouns|color> <value>",message.channel)
            return
        key=args[0].lower()
        value=" ".join(args[1:])
        if key not in ["name","pronouns","color"]:
            await echo("Usage: ~set <name|pronouns|color> <value>",message.channel)
            return
        if key=="color":
            try:color=int(value,16)
            except ValueError:
                await echo("Color must be a valid 6 digit hexadecimal value, e.g. FFAA00.",message.channel)
                return
            if color<0x000000 or color>0xFFFFFF or len(value)!=6:
                await echo("Color must be a valid 6 digit hexadecimal value, e.g. FFAA00.",message.channel)
                return
            users[str(message.author.id)][key]=value.upper()
            save_users(users)
            role=discord.utils.get(message.guild.roles,name=str(message.author.id))
            if role is not None:await role.edit(color=discord.Colour(color))
            await echo(f"I set your color to {value.upper()}!",message.channel)
            return
        users[str(message.author.id)][key]=value
        save_users(users)
        await sync_roles(message.guild)
        await update_nickname(message.author)
        await echo(f"I set your {key} to {value}!",message.channel)
    elif cmd=="flag":
        if not args:
            await echo("Usage: ~flag <hex color code>",message.channel)
            return
        code="".join(args)
        try:
            svg=generate_flag(code,users[str(message.author.id)]["name"])
            svg_file=f"{code}.svg"
            png_file=f"{code}.png"
            with open(svg_file,"w") as file:file.write(svg)
            try:
                cairosvg.svg2png(bytestring=svg.encode("utf-8"),write_to=png_file,output_width=1200)
                await message.channel.send(file=discord.File(png_file,filename=png_file))
            finally:
                if os.path.exists(png_file):os.remove(png_file)
                output_directory=(f"/home/firebot/git/"f"Flags/special/generated/"f"{message.author.name}")
                os.makedirs(output_directory,exist_ok=True)
                destination=os.path.join(output_directory,f"{code}.svg")
                shutil.move(svg_file,destination)
                subprocess.run(["git","sync"])
            await echo(f"You can find the svg version "f"[here](<https://github.com/Fiaguhop137/Flags/blob/main/"f"special/generated/{message.author.name}/{code}.svg>)",message.channel)
        except ValueError as e:await echo(f"Invalid flag code: {e}",message.channel)
        except Exception as e:await echo(f"Failed to generate flag: {e}",message.channel)
    elif cmd=="replay":
        if not args:
            await echo("Usage: ~replay <message count>",message.channel)
            return
        try:lines=int(args[0])
        except ValueError:
            await echo("Message count must be a valid integer.",message.channel)
            return
        try:
            with open(CHAT_LOG_FILE,"r") as chat_log:
                chat_logs=chat_log.readlines()
        except FileNotFoundError:
            await echo("No chat log found.",message.channel)
            return
        if lines<=0:
            await echo("Message count must be a positive integer.",message.channel)
            return
        lines=min(lines,100,len(chat_logs))
        for line in chat_logs[-lines:]:
            await echo(line,message.channel)
    elif cmd=="reboot":
        if LIGHTNING_ROLE_ID not in [role.id for role in message.author.roles]:
            await echo("You are not authorized to use this command.",message.channel)
            return
        await echo("Rebooting...",message.channel)
        reboot="/home/firebot/git/Rainbows-and-Clouds/restart_cirrus.sh"
        os.execv(reboot,[reboot])
    elif cmd=="purge":
        purge_type=args[0].lower() if args else ""
        if purge_type=="bots":
            if CLOUDS_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<2:
                await echo("Usage: ~purge bots <count>",message.channel)
                return
            try:count=int(args[1])
            except ValueError:
                await echo("Count must be a valid integer.",message.channel)
                return
            deleted=await message.channel.purge(limit=count,check=lambda m:m.author.bot)
            await echo(f"Deleted {len(deleted)} bot messages.",message.channel)
        elif purge_type=="user":
            if CLOUDS_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<3:
                await echo("Usage: ~purge user <user_id> <count>",message.channel)
                return
            try:
                user_id=int(args[1])
                count=int(args[2])
            except ValueError:
                await echo("User ID and count must be valid integers.",message.channel)
                return
            deleted=await message.channel.purge(limit=count,check=lambda m:m.author.id==user_id)
            await echo(f"Deleted {len(deleted)} messages from user {user_id}.",message.channel)
        elif purge_type=="nuke":
            if SUN_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            nuke_type=args[1].lower() if len(args)>1 else ""
            if nuke_type=="bots":
                if CLOUDS_ROLE_ID not in [role.id for role in message.author.roles]:
                    await echo("You are not authorized to use this command.",message.channel)
                    return
                while await message.channel.purge(limit=100,check=lambda m:m.author.bot):
                    pass
                await echo("Deleted all bot messages.",message.channel)
            elif nuke_type=="user":
                if CLOUDS_ROLE_ID not in [role.id for role in message.author.roles]:
                    await echo("You are not authorized to use this command.",message.channel)
                    return
                if len(args)<3:
                    await echo("Usage: ~purge nuke user <user_id>",message.channel)
                    return
                try:
                    user_id=int(args[2])
                except ValueError:
                    await echo("User ID must be a valid integer.",message.channel)
                    return
                while await message.channel.purge(limit=100,check=lambda m:m.author.id==user_id):
                    pass
                await echo(f"Deleted all messages from user {user_id}.",message.channel)
            else:
                while await message.channel.purge(limit=100):
                    pass
                await echo("Deleted all messages.",message.channel)
        else:
            if CLOUDS_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<1:
                await echo("Usage: ~purge <count>",message.channel)
                return
            try:count=int(args[0])
            except ValueError:
                await echo("Count must be a valid integer.",message.channel)
                return
            deleted=await message.channel.purge(limit=count)
            await echo(f"Deleted {len(deleted)} messages.",message.channel)
    elif cmd=="role":
        if not args:
            await echo("Usage: ~role <add|remove|new|delete> <args>",message.channel)
            return
        action=args[0].lower()
        if action=="add":
            if len(args)<3:
                return await echo("Usage: ~role add <member> <role>",message.channel)
            if not has_role(message.author,"cloud"):return await echo("You need the cloud role to use this command.",message.channel)
            member=resolve_member(message.guild,args[1])
            if member is None:
                return await echo("Member not found.",message.channel)
            role_name=" ".join(args[2:])
            if role_name not in roles:return await echo(f"Role `{role_name}` does not exist.",message.channel)
            user_id=str(member.id)
            if user_id not in users:
                users[user_id]={"name":"unknown","pronouns":"try ~set or ~help","color":"000000","offenses":"0","roles":[]}
            if "roles" not in users[user_id]:
                users[user_id]["roles"]=[]
            if role_name in users[user_id]["roles"]:
                return await echo(f"{member.mention} already has `{role_name}`.",message.channel)
            users[user_id]["roles"].append(role_name)
            save_users(users)
            await sync_roles(message.guild)
            await echo(f"Added `{role_name}` to {member.mention}.",message.channel)
        elif action=="remove":
            if len(args)<3:
                return await echo("Usage: ~role remove <member> <role>",message.channel)
            if not has_role(message.author,"cloud"):
                return await echo("You need the cloud role to use this command.",message.channel)
            member=resolve_member(message.guild,args[1])
            if member is None:
                return await echo("Member not found.",message.channel)
            role_name=" ".join(args[2:])
            if member.id.__str__() not in users:
                return await echo(f"{member.mention} has no stored roles.",message.channel)
            user_id=str(member.id)
            if role_name not in users[user_id].get("roles",[]):
                return await echo(f"{member.mention} does not have `{role_name}`.",message.channel)
            users[user_id]["roles"].remove(role_name)
            save_users(users)
            await sync_roles(message.guild)
            await echo(f"Removed `{role_name}` from {member.mention}.",message.channel)
        elif action=="new":
            if LIGHTNING_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<2:
                await echo("Usage: ~role new <name> [color]",message.channel)
                return
            role_name=" ".join(args[1:])
            if role_name.isdigit():
                await echo("Numbered role names are reserved for user roles.",message.channel)
                return
            if role_name in roles:
                await echo(f"The role `{role_name}` already exists.",message.channel)
                return
            existing_role=discord.utils.get(message.guild.roles,name=role_name)
            if existing_role is not None:
                await echo(f"A Discord role named `{role_name}` already exists.",message.channel)
                return
            color="000000"
            if len(args)>=3:
                color=args[2].upper()
                if len(color)!=6:
                    await echo("Color must be exactly 6 hexadecimal digits.",message.channel)
                    return
                try:int(color,16)
                except ValueError:
                    await echo("Color must be a valid hexadecimal value.",message.channel)
                    return
            roles[role_name]={"color":color,"permissions":0}
            save_roles(roles)
            await sync_roles(message.guild)
            await echo(f"Created role `{role_name}`.",message.channel)
        elif action=="delete":
            if LIGHTNING_ROLE_ID not in [role.id for role in message.author.roles]:
                await echo("You are not authorized to use this command.",message.channel)
                return
            if len(args)<2:
                await echo("Usage: ~role delete <name>",message.channel)
                return
            role_name=" ".join(args[1:])
            if role_name not in roles:
                await echo(f"Role `{role_name}` does not exist in roles.json.",message.channel)
                return
            roles.pop(role_name)
            save_roles(roles)
            for user in users.values():
                if role_name in user.get("roles",[]):user["roles"].remove(role_name)
            save_users(users)
            discord_role=discord.utils.get(message.guild.roles,name=role_name)
            if discord_role is not None:
                try:await discord_role.delete(reason="Cirrus role deletion")
                except discord.HTTPException as e:
                    await echo(f"Failed to delete Discord role: {e}",message.channel)
                    return
            await sync_roles(message.guild)
            await echo(f"Deleted role `{role_name}`.",message.channel)
        else:await echo("Usage: ~role <add|remove|new|delete> <args>",message.channel)
    else:await echo(f"Unknown command: {cmd}. Type ~help for a list of commands.",message.channel)
@cirrus.event
async def on_guild_join(server:discord.Guild):
    try:
        if server.id!=rainbows_and_clouds_server_id:
            valid_channels=[channel for channel in server.text_channels if(channel.permissions_for(server.me).view_channel and channel.permissions_for(server.me).send_messages)]
            if not valid_channels:raise ValueError("No valid channels found")
            await echo("Why did you add me? This bot is only for the Rainbows and Clouds server.",valid_channels[0])
            raise ValueError("Invalid server found")
        else:await echo("Hello! I'm Cirrus, a discord bot for the Rainbows and Clouds server. Type ~help for a list of commands.",cirrus.get_channel(rainbows_and_clouds_channel_id))
    except:await server.leave()
@cirrus.event
async def on_message(message:discord.Message):
    if message.author==cirrus.user:return
    user_id=str(message.author.id)
    if user_id not in users:
        users[user_id]={"name":"unknown","pronouns":"try ~set or ~help","color":"000000","offenses":"0","roles":[]}
        save_users(users)
    changed=False
    if "roles" not in users[user_id]:
        users[user_id]["roles"]=[]
        changed=True
    if "offenses" not in users[user_id]:
        users[user_id]["offenses"]="0"
        changed=True
    try:int(users[user_id]["offenses"])
    except (ValueError,TypeError):
        users[user_id]["offenses"]="0"
        changed=True
    if changed:save_users(users)
    violations=users[user_id]["offenses"]
    if message.guild is None:
        await message.author.send("I don't support DMs. Please use me in the Rainbows and Clouds server.")
        return
    if message.author.bot:await asyncio.sleep(1)
    parts=message.content.split()
    if not parts:return
    cmd=parts[0]
    args=parts[1:]
    with open(CHAT_LOG_FILE,"r") as chat_log:
        lines=chat_log.readlines()
        if lines:
            last_line=lines[-1]
            try:
                last_message=last_line.split("):")[-1].strip()
                last_author=(last_line.split("(")[-1].split(")")[0].strip())
                if(message.content.strip()==last_message and last_author==user_id):
                    await message.delete()
                    users[user_id]["offenses"]=str(int(users[user_id]["offenses"])+1)
                    save_users(users)
            except(IndexError,ValueError):pass
    with open(CHAT_LOG_FILE,"a") as chat_log:chat_log.write(f"[{datetime.datetime.now(ZoneInfo('America/New_York')).isoformat()}, "f"{message.guild}/{message.channel}] "f"{message.author}({message.author.id}): "f"{message.content}\n")
    if banned_words.search(message.content):
        await message.delete()
        await echo(f"{message.author.mention}, that message was flagged as offensive, inappropriate, and/or vulgar. Ping a cloud if you believe this is a mistake.",message.channel)
        await echo(f"Deleted message from {message.author} in {message.guild}/{message.channel}: {message.content}",cirrus.get_channel(clouds_channel_id))
        users[user_id]["offenses"]=str(int(users[user_id]["offenses"])+1)
        save_users(users)
    if violations!=users[user_id]["offenses"]:
        violations=users[user_id]["offenses"]
        if int(violations)>5:
            await echo(f"{message.author.mention}, you have been muted for repeated violations(e.g., spamming, hate speech, etc.). Please contact a cloud if you believe this is a mistake.",message.channel)
            await echo(f"{message.author} has been muted for {violations} violations.",cirrus.get_channel(clouds_channel_id))
            await message.author.edit(timed_out_until=(discord.utils.utcnow()+datetime.timedelta(seconds=int(violations)*10)),reason=f"{violations} violations of the rules.")
        return
    else:
        current_offenses=int(users[user_id]["offenses"])
        if current_offenses>0:users[user_id]["offenses"]=str(current_offenses-1)
        save_users(users)
    await sync_roles(message.guild)
    await update_nickname(message.author)
    await run_cmd(cmd,args,message)
    await sync_roles(message.guild)
    await update_nickname(message.author)
@cirrus.event
async def on_member_join(member:discord.Member):
    await sync_roles(member.guild)
    await update_nickname(member)
    await echo(f"Hi {member.mention}! Welcome to the Rainbows and Clouds server! Type ~help for a list of commands. ",cirrus.get_channel(rainbows_and_clouds_channel_id))
@cirrus.event
async def on_member_update(before:discord.Member,after:discord.Member):
    if before.nick!=after.nick:
        await update_nickname(after)
@cirrus.event
async def on_ready():
    server=cirrus.get_guild(rainbows_and_clouds_server_id)
    if server is None:
        return
    await sync_roles(server)
    for user in server.members:
        await update_nickname(user)
    await echo("Cirrus has rebooted! Type ~help for a list of commands.",cirrus.get_channel(rainbows_and_clouds_channel_id))
cirrus.run(TOKEN)